### ISSUE TITLE
Bug: colorized output is breaking on some shell clients (ie. Wezterm)

### ISSUE THREAD

**Issue by leonardomerlin** [qoomon/zsh-jumper#3]
Hi, first of all, thanks for this amazing plugin. I've been using it for a while. Previously I was using with [hyperjs](https://hyper.is/). Recently I started to try [WezTerm](https://wezfurlong.org/wezterm/), but the colorized option is failing on it.

Here is an example of the output:
```zsh
➜  ~ j exp
zjump:cd:74: no such file or directory: ^[[1m^[[36m/Users/leonardomerlin/projects/experiments^[[39;49m^[[0m
```

If I manually edit [the script](https://github.com/qoomon/zjump/blob/master/zjump.zsh#L81) and remove the `--color=always` flag, it works fine.

Do you think that would be possible to make the colors optional? Something that we can disable via some env variable... (I'm not sure if this is already possible, btw. I'm still learning about it)

**Comment by qoomon** [comment]
could you try to add `--ansi` to fzf command?

**Comment by qoomon** [comment]
I can't reproduce this error on my machine (MacOS Ventura, WezTerm Version 20230408-112425-69ae8472)

**Comment by qoomon** [comment]
@leonardomerlin please reopen if issue still occurs.

**Comment by QuantumBJump** [comment]
Hi! I use gnome terminal and was encountering this same problem. adding `--ansi` to the fzf command did indeed fix the problem!

edit: op's workaround, to remove `--color=always`, also fixed the jump behaviour, but adding `--ansi` also preserves colorisation

**Comment by qoomon** [comment]
I'll fix it

**Comment by qoomon** [comment]
I added the `--ansi` to `fzf` command. feel free to test

**Comment by QuantumBJump** [comment]
Yep! pulling from master the problem seems to be fixed on my end
